spring:
    application:
        name: snapit-notification

    rabbitmq:
        host: ab6737414eea54b5fbbf7d8071ae75d1-1338972412.us-east-1.elb.amazonaws.com
        port: 5672
        username: hexqueue
        password: 1xo4r9VIU4ARLW3f

mail:
    smtp:
        host: smtp.gmail.com
        port: 587
        auth: true
        starttls-enable: true
    authentication:
        user: snapit.postech@gmail.com
        password: lzwnbsaibkjycnjf

management:
    server:
        port: 28082
    endpoint:
        health:
            probes:
                enabled: true
    health:
        livenessstate:
            enabled: true
        readinessstate:
            enabled: true
