spring:
    application:
        name: snapit-notification

    rabbitmq:
        host: a5c26c3dc1a9746a0a098ca86b70b402-1576489231.us-east-1.elb.amazonaws.com
        port: 5672
        username: hexqueue
        password: 1xo4r9VIU4ARLW3f

mail:
    smtp:
        host: smtp.gmail.com
        port: 587
        auth: true
        starttls-enable: true
    authentication:
        user: snapit.postech@gmail.com
        password: lzwnbsaibkjycnjf

management:
    endpoint:
        health:
            probes:
                enabled: true
    health:
        livenessstate:
            enabled: true
        readinessstate:
            enabled: true
