spring:
    application:
        name: snapit-notification

    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest

mail:
    smtp:
        host: smtp.gmail.com
        port: 587
        auth: true
        starttls-enable: true
    authentication:
        user: snapit.postech@gmail.com
        password: lzwnbsaibkjycnjf