# {{- if .Values.configMap.enabled }}
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: {{ include "default-chart.fullname" . }}-cm
#   labels:
#     app: {{ .Values.chartName }}
# data:
#   {{- range $key, $value := .Values.configMap.data }}
#   {{ $key }}: {{ $value | quote }}
#   {{- end }}
# {{- end }}