name: Terraform Plan

on:
  pull_request:

env:
  pr_number: ${{ github.event.number }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: SonarQube - Quality Gate
        uses: ./.github/quality/quality-gate
        with:
          sonarqube_token: ${{ secrets.SONAR_TOKEN }}